spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcoursecluster.ksop0qu.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course
